version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oumayma404!!!!
      POSTGRES_DB: sportscoach
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./wwwroot/uploads:/app/wwwroot/uploads  # Mount local 'uploads' to container

  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__PostgreSQLConnection=Host=db;Database=sportscoach;Username=postgres;Password=oumayma404!!!!

volumes:
  postgres_data: